SOURCES = [
    {"url": "https://www.nvidia.com/en-us/startups/", "tecnologia": "Inception", "titulo": ""},
    {"url": "https://www.nvidia.com/en-us/ai-data-science/products/nim-microservices/", "tecnologia": "NIM", "titulo": ""},
    {"url": "https://www.nvidia.com/en-us/ai-data-science/products/nemo/", "tecnologia": "NeMo", "titulo": ""},
    {"url": "https://github.com/NVIDIA/NeMo-Guardrails", "tecnologia": "NeMo Guardrails", "titulo": ""},
    {"url": "https://developer.nvidia.com/triton-inference-server", "tecnologia": "Triton", "titulo": ""},
    {"url": "https://github.com/NVIDIA/TensorRT-LLM", "tecnologia": "TensorRT-LLM", "titulo": ""},
    {"url": "https://rapids.ai/", "tecnologia": "RAPIDS", "titulo": ""},
    {"url": "https://docs.rapids.ai/api/cudf/stable/", "tecnologia": "cuDF", "titulo": ""},
    {"url": "https://docs.rapids.ai/api/cuml/stable/", "tecnologia": "cuML", "titulo": ""},
    {"url": "https://developer.nvidia.com/cuda-toolkit", "tecnologia": "CUDA", "titulo": ""},
    {"url": "https://developer.nvidia.com/riva", "tecnologia": "Riva", "titulo": ""},
    {"url": "https://www.nvidia.com/en-us/omniverse/", "tecnologia": "Omniverse", "titulo": ""},
    {"url": "https://developer.nvidia.com/isaac", "tecnologia": "Isaac", "titulo": ""},
    {"url": "https://www.nvidia.com/en-us/clara/", "tecnologia": "Clara", "titulo": ""},
    {"url": "https://developer.nvidia.com/morpheus-cybersecurity", "tecnologia": "Morpheus", "titulo": ""},
    {"url": "https://www.nvidia.com/en-us/data-center/products/ai-enterprise/", "tecnologia": "AI Enterprise", "titulo": ""},
    {"url": "https://blogs.nvidia.com/blog/ai-5-layer-cake/", "tecnologia": "Estrategico", "titulo": ""},
    {"url": "https://sequoiacap.com/article/services-the-new-software/", "tecnologia": "Estrategico", "titulo": ""},
    {"url": "https://www.emcap.com/thoughts/the-ai-native-services-playbook", "tecnologia": "Estrategico", "titulo": ""},
]
